---
language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t lkececi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lkececi/react-test npm test

after_success:
  - docker build -t lkececi/multi-client ./client
  - docker build -t lkececi/multi-nginx ./nginx
  - docker build -t lkececi/multi-server ./server
  - docker build -t lkececi/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push lkececi/multi-client
  - docker push lkececi/multi-nginx
  - docker push lkececi/multi-server
  - docker push lkececi/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-854597615242"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"